# Generated by Django 5.2.8 on 2025-11-12 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name="Numéro d'Étudiant")),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom Complet')),
                ('year', models.CharField(max_length=10, verbose_name="Niveau d'Études")),
                ('password_clear', models.CharField(max_length=50, verbose_name='Mot de passe (Clear Text)')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
    ]
