# Generated by Django 5.2.8 on 2025-11-13 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du Cours')),
                ('teacher', models.CharField(blank=True, max_length=100, verbose_name='Professeur')),
            ],
            options={
                'verbose_name': 'Cours',
                'verbose_name_plural': 'Cours',
            },
        ),
        migrations.CreateModel(
            name='ForumChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nom du Canal')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Canal de Forum',
                'verbose_name_plural': 'Canaux de Forum',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name="Titre de l'Événement")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_time', models.DateTimeField(verbose_name='Heure de Début')),
                ('end_time', models.DateTimeField(verbose_name='Heure de Fin')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='Lieu')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.course', verbose_name='Cours Associé')),
            ],
            options={
                'verbose_name': 'Événement',
                'verbose_name_plural': 'Événements',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name="Numéro d'Étudiant")),
                ('email', models.EmailField(max_length=254, verbose_name='Adresse Email')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nom Complet')),
                ('year', models.CharField(max_length=10, verbose_name="Niveau d'Études")),
                ('password_clear', models.CharField(max_length=50, verbose_name='Mot de passe (Clear Text)')),
                ('enrolled_courses', models.ManyToManyField(blank=True, related_name='students_enrolled', to='dashboard.course', verbose_name='Cours Inscrits')),
            ],
            options={
                'verbose_name': 'Étudiant',
                'verbose_name_plural': 'Étudiants',
            },
        ),
        migrations.CreateModel(
            name='ForumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Contenu du Message')),
                ('posted_at', models.DateTimeField(auto_now_add=True, verbose_name='Date du Post')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='dashboard.forumchannel', verbose_name='Canal')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_posts', to='dashboard.student', verbose_name='Auteur')),
            ],
            options={
                'verbose_name': 'Post de Forum',
                'verbose_name_plural': 'Posts de Forum',
                'ordering': ['posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Objet')),
                ('body', models.TextField(verbose_name='Contenu')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'envoi")),
                ('is_read', models.BooleanField(default=False, verbose_name='Lu')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_emails', to='dashboard.student', verbose_name='Destinataire')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_emails', to='dashboard.student', verbose_name='Expéditeur')),
            ],
            options={
                'verbose_name': 'Email',
                'verbose_name_plural': 'Emails',
                'ordering': ['-sent_at'],
            },
        ),
    ]
