# Generated by Django 5.2.8 on 2025-11-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_email_is_draft_alter_email_recipient'),
        ('dashboard', '0003_forumreaction'),
    ]

    operations = [
    ]
