# Generated by Django 5.2.8 on 2025-12-04 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_forumreaction"),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumPostRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("read_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_by",
                        to="dashboard.forumpost",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_posts",
                        to="dashboard.student",
                    ),
                ),
            ],
            options={
                "unique_together": {("post", "student")},
            },
        ),
    ]
