# Generated by Django 5.2.8 on 2025-11-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_merge_20251125_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumattachment',
            name='original_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
