# Generated by Django 5.2.8 on 2025-11-25 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_forumattachment_original_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumpost',
            name='title',
        ),
        migrations.AlterField(
            model_name='forumpost',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
